Loading trainer: ZeroshotCLIP
Loading dataset: ImageNet
Traceback (most recent call last):
  File "train.py", line 252, in <module>
    main(args)
  File "train.py", line 173, in main
    trainer = build_trainer(cfg)
  File "/mlainas/yewon/CoOp/CoOp/KGPrompt/dassl/engine/build.py", line 11, in build_trainer
    return TRAINER_REGISTRY.get(cfg.TRAINER.NAME)(cfg)
  File "/mlainas/yewon/CoOp/CoOp/KGPrompt/dassl/engine/trainer.py", line 344, in __init__
    self.build_data_loader()
  File "/mlainas/yewon/CoOp/CoOp/KGPrompt/dassl/engine/trainer.py", line 401, in build_data_loader
    dm = DataManager(self.cfg)
  File "/mlainas/yewon/CoOp/CoOp/KGPrompt/dassl/data/data_manager.py", line 62, in __init__
    dataset = build_dataset(cfg)
  File "/mlainas/yewon/CoOp/CoOp/KGPrompt/dassl/data/datasets/build.py", line 11, in build_dataset
    return DATASET_REGISTRY.get(cfg.DATASET.NAME)(cfg)
  File "/mlainas/yewon/CoOp/CoOp/KGPrompt/datasets/imagenet.py", line 22, in __init__
    mkdir_if_missing(self.split_fewshot_dir)
  File "/mlainas/yewon/CoOp/CoOp/KGPrompt/dassl/utils/tools.py", line 38, in mkdir_if_missing
    os.makedirs(dirname)
  File "/home/yeyewon/anaconda3/envs/torch/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/yeyewon/anaconda3/envs/torch/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/yeyewon/anaconda3/envs/torch/lib/python3.8/os.py", line 213, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/yeyewon/anaconda3/envs/torch/lib/python3.8/os.py", line 223, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data'